import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Bot, Check, CheckCircle2, Clock3, Copy, FileText, Fingerprint, Pencil, ShieldCheck, Sparkles, X } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api, compactHash, dateTime, money } from '../api';
import type { Role } from '../types';
import { SeverityBadge, Skeleton } from '../components/Common';

type Detail = { loan: Record<string, unknown>; exceptions: Array<Record<string, unknown>>; recommendations: Array<Record<string, unknown>>; reviews: Array<Record<string, unknown>>; audit: Array<Record<string, unknown>>; auditIntegrity: { valid: boolean; count: number; head: string }; verified?: Record<string, unknown> };

export function LoanDetail({ role }: { role: Role }) {
  const { id } = useParams(); const [detail, setDetail] = useState<Detail | null>(null); const [tab, setTab] = useState<'record'|'evidence'|'audit'>('record'); const [busy, setBusy] = useState(''); const [toast, setToast] = useState(''); const [editMode, setEditMode] = useState(false); const [draft, setDraft] = useState<Record<string,string>>({}); const [reviewNote, setReviewNote] = useState('');
  const refresh = () => api<Detail>(`/loans/${id}`).then(setDetail);
  useEffect(() => { refresh(); }, [id]);
  const recommendations = useMemo(() => new Map(detail?.recommendations.map((value) => [value.exception_id, value]) ?? []), [detail?.recommendations]);
  async function askAI(exceptionId: unknown) { setBusy(`ai-${exceptionId}`); await api(`/exceptions/${exceptionId}/ai`, { method: 'POST', body: JSON.stringify({ actorId: 2 }) }); await refresh(); setBusy(''); setToast('AI evidence prepared for human review.'); }
  async function actAI(recId: unknown, action: string) { setBusy(`rec-${recId}`); await api(`/ai/${recId}/action`, { method: 'POST', body: JSON.stringify({ actorId: 2, action }) }); await refresh(); setBusy(''); setToast(`Suggestion ${action}. No data changed.`); }
  async function decide(decision: string) { const comment = reviewNote || (decision === 'approved' ? 'Evidence reviewed. Record accepted for verified dataset.' : 'Record routed for follow-up.'); setBusy('decision'); await api(`/loans/${id}/review`, { method: 'POST', body: JSON.stringify({ reviewerId: 2, decision, comment }) }); await refresh(); setReviewNote(''); setBusy(''); setToast(decision === 'approved' ? 'Record sealed and added to verified dataset.' : 'Reviewer decision recorded.'); }
  if (!detail) return <Skeleton rows={8}/>;
  const loan = detail.loan;
  const fields = [['Loan ID','loan_id'],['Borrower ID','borrower_id'],['Loan type','loan_type'],['Origination','origination_date'],['Maturity','maturity_date'],['Original principal','original_principal'],['Current balance','current_balance'],['Interest rate','interest_rate'],['Payment status','payment_status'],['Days past due','days_past_due'],['Borrower state','borrower_state'],['Document status','document_status'],['Servicer','servicer_name'],['Source system','source_system']] as const;
  const editable = new Set(['current_balance','payment_status','borrower_state','document_status']);
  function beginEdit() { setDraft(Object.fromEntries([...editable].map((key) => [key, String(loan[key] ?? '')]))); setEditMode(true); }
  async function saveEdits() { setBusy('edit'); try { await api(`/loans/${id}`, { method: 'PATCH', body: JSON.stringify({ actorId: 2, changes: draft }) }); await refresh(); setEditMode(false); setToast('Fields updated, revalidated, and added to the audit chain.'); } catch (error) { setToast(error instanceof Error ? error.message : 'Unable to save changes.'); } finally { setBusy(''); } }
  return <div className="page-stack detail-page">{toast ? <button className="toast" onClick={() => setToast('')}><CheckCircle2 size={17}/>{toast}<X size={15}/></button> : null}<Link to="/exceptions" className="back-link"><ArrowLeft size={16}/> Back to queue</Link>
    <section className="loan-title"><div><span className="loan-type">{String(loan.loan_type).replaceAll('_',' ')}</span><h1>{String(loan.loan_id ?? 'Missing loan ID')}</h1><p>{String(loan.borrower_id)} · {String(loan.servicer_name)}</p></div><div className="title-badges">{detail.verified ? <span className="verified-seal"><ShieldCheck/> Verified & sealed</span> : <span className="exception-count">{detail.exceptions.filter((value) => value.status === 'open').length} open exceptions</span>}<span className="integrity"><Fingerprint size={16}/> Chain {detail.auditIntegrity.valid ? 'valid' : 'broken'}</span></div></section>
    <nav className="tabs" aria-label="Loan detail sections">{(['record','evidence','audit'] as const).map((value) => <button className={tab === value ? 'active' : ''} onClick={() => setTab(value)} key={value}>{value === 'record' ? 'Canonical record' : value === 'evidence' ? `Exceptions & AI (${detail.exceptions.length})` : `Audit timeline (${detail.auditIntegrity.count})`}</button>)}</nav>
    {tab === 'record' ? <div className="detail-grid"><article className="panel"><header className="panel-header"><div><span className="panel-icon"><FileText size={18}/></span><div><h3>Normalized loan data</h3><p>Mapped from {String(loan.filename)} · source row {String(loan.row_number)}</p></div></div>{role === 'reviewer' ? editMode ? <span className="edit-actions"><button className="button subtle" onClick={() => setEditMode(false)}>Cancel</button><button className="button primary" disabled={busy === 'edit'} onClick={saveEdits}>Save & revalidate</button></span> : <button className="button subtle" onClick={beginEdit}><Pencil size={14}/> Edit fields</button> : null}</header><dl className="record-grid">{fields.map(([label,key]) => <div key={key}><dt>{label}{editMode && editable.has(key) ? <em> editable</em> : null}</dt><dd>{editMode && editable.has(key) ? <input aria-label={`Edit ${label}`} value={draft[key] ?? ''} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.target.value }))}/> : key.includes('principal') || key.includes('balance') ? (loan[key] == null ? '—' : money.format(Number(loan[key]))) : key === 'interest_rate' ? `${(Number(loan[key]) * 100).toFixed(2)}%` : String(loan[key] ?? '—')}</dd></div>)}</dl><div className="lineage-strip"><Fingerprint size={18}/><div><strong>Source fingerprint</strong><code>{String(loan.source_hash)}</code></div><button onClick={() => navigator.clipboard.writeText(String(loan.source_hash))} aria-label="Copy source hash"><Copy size={15}/></button></div></article>
      <aside className="panel review-card"><div className="review-head"><ShieldCheck/><h3>Human decision</h3><p>AI suggestions never modify this record automatically.</p></div>{detail.verified ? <div className="sealed-card"><CheckCircle2/><strong>Approved and verified</strong><span>{dateTime(String(detail.verified.verified_at))}</span><code>{compactHash(String(detail.verified.record_hash))}</code></div> : role === 'reviewer' ? <><textarea value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} placeholder="Optional reviewer note" aria-label="Reviewer note"/><button disabled={busy === 'decision'} className="button approve" onClick={() => decide('approved')}><Check/> Approve & verify</button><button disabled={busy === 'decision'} className="button correction" onClick={() => decide('correction_requested')}>Request correction</button><button disabled={busy === 'decision'} className="button reject" onClick={() => decide('rejected')}>Reject record</button></> : <p className="muted-copy">Switch to the Reviewer role to record a final decision.</p>}</aside></div> : null}
    {tab === 'evidence' ? <div className="evidence-list">{detail.exceptions.map((exception) => { const rec = recommendations.get(exception.id); return <article className="panel exception-detail" key={String(exception.id)}><header><SeverityBadge severity={String(exception.severity)}/><div><h3>{String(exception.rule_code).replaceAll('_',' ')}</h3><p>{String(exception.message)}</p></div><span className={`status ${exception.status === 'open' ? 'danger' : 'success'}`}><i/>{String(exception.status).replaceAll('_',' ')}</span></header><div className="evidence-values"><div><span>Field</span><strong>{String(exception.field_name ?? 'Record-level')}</strong></div><div><span>Observed</span><code>{String(exception.current_value ?? 'empty')}</code></div><div><span>Rule suggestion</span><code>{String(exception.suggested_value ?? 'manual evidence required')}</code></div></div>{rec ? <div className="ai-panel"><div className="ai-label"><span><Bot size={17}/></span><div><strong>Veritas AI analysis</strong><small>{String(rec.model)} · {(Number(rec.confidence) * 100).toFixed(0)}% confidence · {dateTime(String(rec.created_at))}</small></div><span className={`status ${rec.status === 'pending' ? 'warning' : 'success'}`}><i/>{String(rec.status)}</span></div><p>{String(rec.explanation)}</p><blockquote>{String(rec.recommendation)}</blockquote><details><summary>Prompt & control metadata</summary><code>{String(rec.prompt)}</code></details>{rec.status === 'pending' && role === 'reviewer' ? <div className="ai-actions"><button disabled={busy === `rec-${rec.id}`} className="button approve" onClick={() => actAI(rec.id,'accepted')}><Check/> Accept guidance</button><button disabled={busy === `rec-${rec.id}`} className="button subtle" onClick={() => actAI(rec.id,'edited')}><Pencil/> Mark edited</button><button disabled={busy === `rec-${rec.id}`} className="button reject" onClick={() => actAI(rec.id,'rejected')}><X/> Reject</button><small>These actions log your judgment; they do not silently change loan data.</small></div> : null}</div> : <button className="button ai-button" disabled={busy === `ai-${exception.id}`} onClick={() => askAI(exception.id)}><Sparkles size={16}/>{busy === `ai-${exception.id}` ? 'Analyzing evidence…' : 'Generate AI explanation'}</button>}</article>; })}</div> : null}
    {tab === 'audit' ? <article className="panel audit-panel"><div className="audit-proof"><Fingerprint/><div><strong>Cryptographic event chain verified</strong><p>{detail.auditIntegrity.count} events · head {compactHash(detail.auditIntegrity.head ?? '')}</p></div><span><Check/> Valid</span></div><ol className="timeline">{detail.audit.map((event) => <li key={String(event.id)}><span className="timeline-dot"><Clock3 size={14}/></span><div><div><strong>{String(event.event_type).replaceAll('_',' ')}</strong><time>{dateTime(String(event.created_at))}</time></div><p>{String(event.description)}</p><small>{String(event.actor_name ?? 'System')} · <code>{compactHash(String(event.event_hash))}</code></small></div></li>)}</ol></article> : null}
  </div>;
}
