import { useEffect, useState } from 'react';
import { ArrowRight, Download, Fingerprint, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, compactHash, dateTime, money } from '../api';
import { EmptyState, Skeleton } from '../components/Common';

type Verified = { id: number; loan_row_id: number; loan_id: string; borrower_id: string; loan_type: string; original_principal: number; current_balance: number; borrower_state: string; record_hash: string; verified_at: string; verified_by_name: string; filename: string };
export function VerifiedRecords() {
  const [rows,setRows] = useState<Verified[] | null>(null); useEffect(() => { api<Verified[]>('/verified-loans').then(setRows); }, []);
  return <div className="page-stack"><section className="hero-row"><div><p className="kicker"><span/> TRUSTED DATA PRODUCT</p><h1>Verified. Traceable. Ready downstream.</h1><p>Human-approved canonical records with tamper-evident evidence.</p></div><div className="hero-actions"><a className="button subtle" href="/api/export/audit.csv"><Download size={15}/> Audit trail</a><a className="button primary" href="/api/export/verified.csv"><Download size={15}/> Export verified CSV</a></div></section>
    <div className="verified-banner"><ShieldCheck/><div><strong>Every export carries its proof.</strong><p>Each canonical record is chained to the prior verification using SHA-256.</p></div><span>{rows?.length ?? 0} sealed records</span></div><article className="panel"><div className="table-scroll">{!rows ? <Skeleton/> : rows.length === 0 ? <EmptyState title="No verified records yet" body="Approve a record from the Reviewer workspace to create the first sealed record."/> : <table><thead><tr><th>Verified loan</th><th>Borrower</th><th>Principal</th><th>Balance</th><th>Verified by</th><th>Record proof</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><span className="verified-loan"><ShieldCheck/><span><strong>{row.loan_id}</strong><small>{row.loan_type.replaceAll('_',' ')} · {row.borrower_state}</small></span></span></td><td>{row.borrower_id}</td><td>{money.format(row.original_principal)}</td><td>{money.format(row.current_balance)}</td><td><strong>{row.verified_by_name}</strong><small className="table-sub">{dateTime(row.verified_at)}</small></td><td><span className="proof"><Fingerprint size={14}/><code>{compactHash(row.record_hash)}</code></span></td><td><Link aria-label={`Open verified loan ${row.loan_id}`} className="row-action" to={`/loans/${row.loan_row_id}`}><ArrowRight size={17}/></Link></td></tr>)}</tbody></table>}</div></article>
  </div>;
}
